dist: trusty
sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_fe7d4190ec44_key -iv $encrypted_fe7d4190ec44_iv -in id_rsa.travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - sudo sysctl -w vm.max_map_count=262144

stages:
  - name: test

jobs:
  include:
    - stage: test
      name: Fedora - 28
      env:
      script:
        - test/test-setup.sh fedora

    - stage: test
      name: Debian Stretch - 9.0
      env:
      script:
      - test/test-setup.sh debian

    - stage: test
      name: ubuntu bionic
      env:
      script:
        - test/test-setup.sh ubuntu

    - stage: test
      name: macosx
      env:
      script:
        - test/send2mac.sh

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: setupsh-badges
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
